name: Alpine
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-alpine:    
    runs-on: ubuntu-latest # or any other OS
    container:
      image: alpine:latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        apk add --no-cache cmake gcc g++ make git openssl openssl-dev protobuf-dev protobuf gtest-dev gtest benchmark-dev benchmark

    - name: Build project
      run: |
        mkdir build
        cd build
        cmake ..
        make && make install